let editingProductId=null;

function specialFieldsHTML(){const type=window.currentBusiness?.businessType;let html="";
if(type==="clothing") html=`<div class="special-box"><h3>👕 Datos de ropa</h3><div class="mini-grid"><div class="form-group"><label>Tallas</label><input id="specialSizes" placeholder="S, M, L, XL"></div><div class="form-group"><label>Colores</label><input id="specialColors" placeholder="Negro, Blanco, Azul"></div></div></div>`;
else if(type==="restaurant") html=`<div class="special-box"><h3>🍔 Datos de restaurante</h3><div class="mini-grid"><div class="form-group"><label>Ingredientes</label><input id="specialIngredients" placeholder="Pan, carne, queso"></div><div class="form-group"><label>Extras</label><input id="specialExtras" placeholder="Queso, tocineta"></div></div></div>`;
else if(type==="pharmacy") html=`<div class="special-box"><h3>💊 Datos de farmacia</h3><div class="mini-grid"><div class="form-group"><label>Lote</label><input id="specialBatch"></div><div class="form-group"><label>Vencimiento</label><input id="specialExpiration" type="date"></div></div></div>`;
else if(type==="workshop") html=`<div class="special-box"><h3>🔧 Datos de taller</h3><div class="mini-grid"><div class="form-group"><label>Marca</label><input id="specialBrand"></div><div class="form-group"><label>Referencia</label><input id="specialReference"></div></div></div>`;
else if(type==="veterinary") html=`<div class="special-box"><h3>🐶 Datos veterinarios</h3><div class="mini-grid"><div class="form-group"><label>Especie</label><input id="specialSpecies" placeholder="Perro, gato..."></div><div class="form-group"><label>Servicio asociado</label><input id="specialService"></div></div></div>`;
else if(type==="icecream") html=`<div class="special-box"><h3>🍦 Datos de heladería</h3><div class="mini-grid"><div class="form-group"><label>Sabor</label><input id="specialFlavor"></div><div class="form-group"><label>Tamaño</label><input id="specialSize" placeholder="Pequeño, mediano, grande"></div></div></div>`;
return html}

function showProducts(){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.getElementById("productsPage").classList.add("active");setPageHeader("📦","Productos","Administra productos, precios y existencias");setActiveNav("products");loadCategories();loadProducts();closeSidebar()}
function showInventory(){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.getElementById("inventoryPage").classList.add("active");setPageHeader("📊","Inventario","Control de existencias y stock bajo");setActiveNav("inventory");loadInventory();closeSidebar()}

async function loadCategories(){const products=await dbGetAll("products"),select=document.getElementById("categoryFilter"),current=select.value;const cats=[...new Set(products.map(p=>p.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b));select.innerHTML='<option value="">Todas las categorías</option>'+cats.map(c=>`<option value="${escapeHtml(c)}">${escapeHtml(c)}</option>`).join("");select.value=current}

async function loadProducts(){const products=await dbGetAll("products"),q=document.getElementById("productSearch").value.trim().toLowerCase(),cat=document.getElementById("categoryFilter").value;const filtered=products.filter(p=>(!q||`${p.name} ${p.sku||""} ${p.category||""}`.toLowerCase().includes(q))&&(!cat||p.category===cat)).sort((a,b)=>a.name.localeCompare(b.name));const c=document.getElementById("productsList");if(!filtered.length){c.innerHTML=`<div class="empty-list"><div>📦</div><h3>No hay productos</h3><p>Crea tu primer producto para comenzar.</p><button class="primary-button compact" onclick="openProductForm()">＋ Nuevo producto</button></div>`;return}c.innerHTML=filtered.map(productCard).join("")}

function productCard(p){const low=Number(p.stock)<=Number(p.minStock||0),price=formatMoney(p.price);return `<article class="product-card"><div class="product-main"><div class="product-avatar">${escapeHtml(p.icon||"📦")}</div><div class="product-info"><h3>${escapeHtml(p.name)}</h3><p>${escapeHtml(p.category||"Sin categoría")} ${p.sku?`• SKU ${escapeHtml(p.sku)}`:""}</p></div></div><div class="product-numbers"><div><span>Precio</span><strong>${price}</strong></div><div><span>Stock</span><strong class="${low?"stock-low":""}">${p.stock}</strong></div></div><div class="product-actions"><button onclick="openProductForm(${p.id})">✏️</button><button class="danger-action" onclick="deleteProduct(${p.id})">🗑️</button></div></article>`}

function escapeHtml(value){return String(value??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}

function openProductForm(id=null){editingProductId=id;document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.getElementById("productFormPage").classList.add("active");setPageHeader("📦",id?"Editar producto":"Nuevo producto","Información del producto");setActiveNav("products");document.getElementById("productFormTitle").textContent=id?"✏️ Editar producto":"➕ Nuevo producto";document.getElementById("specialFields").innerHTML=specialFieldsHTML();document.getElementById("productForm").reset();document.getElementById("productId").value=id||"";if(id)fillProduct(id);closeSidebar()}

async function fillProduct(id){const p=await dbGet("products",id);if(!p)return;document.getElementById("productName").value=p.name||"";document.getElementById("productSku").value=p.sku||"";document.getElementById("productCategory").value=p.category||"";document.getElementById("productCost").value=p.cost||0;document.getElementById("productPrice").value=p.price||0;document.getElementById("productStock").value=p.stock||0;document.getElementById("productMinStock").value=p.minStock||0;document.getElementById("productDescription").value=p.description||"";Object.entries(p.special||{}).forEach(([k,v])=>{const el=document.getElementById(k);if(el)el.value=v})}

async function saveProduct(e){e.preventDefault();const name=document.getElementById("productName").value.trim(),sku=document.getElementById("productSku").value.trim(),category=document.getElementById("productCategory").value.trim(),cost=Number(document.getElementById("productCost").value||0),price=Number(document.getElementById("productPrice").value||0),stock=Number(document.getElementById("productStock").value||0),minStock=Number(document.getElementById("productMinStock").value||0),description=document.getElementById("productDescription").value.trim();if(!name||price<0){showToast("⚠️ Completa el nombre y precio");return}const special={};document.querySelectorAll("#specialFields input").forEach(el=>{if(el.id)special[el.id]=el.value});let product=editingProductId?await dbGet("products",editingProductId):null;const oldStock=product?Number(product.stock||0):0;product={...(product||{}),name,sku,category,cost,price,stock,minStock,description,special,icon:window.currentBusiness.businessIcon==="👕"?"👕":"📦",updatedAt:new Date().toISOString(),createdAt:product?.createdAt||new Date().toISOString()};if(editingProductId)product.id=editingProductId;const id=await dbPut("products",product);const diff=stock-oldStock;if(diff!==0){await dbPut("inventoryMovements",{productId:id,type:editingProductId?"adjustment":"initial",quantity:diff,previousStock:oldStock,newStock:stock,date:new Date().toISOString()})}showToast(editingProductId?"✅ Producto actualizado":"🎉 Producto creado");editingProductId=null;await updateDashboard();showProducts()}

async function deleteProduct(id){const p=await dbGet("products",id);if(!p)return;if(!confirm(`¿Eliminar "${p.name}"?`))return;await dbDelete("products",id);showToast("🗑️ Producto eliminado");await updateDashboard();loadProducts();loadCategories()}

async function loadInventory(){const products=await dbGetAll("products"),low=products.filter(p=>Number(p.stock)<=Number(p.minStock||0)),total=products.reduce((s,p)=>s+Number(p.stock||0),0);document.getElementById("inventorySummary").innerHTML=`<div class="inventory-chip"><span>📦 Productos</span><strong>${products.length}</strong></div><div class="inventory-chip"><span>📊 Unidades</span><strong>${total}</strong></div><div class="inventory-chip warning"><span>⚠️ Stock bajo</span><strong>${low.length}</strong></div>`;document.getElementById("inventoryList").innerHTML=products.sort((a,b)=>Number(a.stock)-Number(b.stock)).map(productCard).join("")||`<div class="empty-list"><div>📊</div><h3>Inventario vacío</h3><p>Aún no tienes productos.</p></div>`}

document.getElementById("newProductButton").onclick=()=>openProductForm();
document.getElementById("cancelProduct").onclick=showProducts;
document.getElementById("productForm").addEventListener("submit",saveProduct);
document.getElementById("productSearch").addEventListener("input",loadProducts);
document.getElementById("categoryFilter").addEventListener("change",loadProducts);
